version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  test-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password_test
      POSTGRES_DATABASE: postgres_test
    ports:
      - "5431:5432"
  web:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
  front:
    build: ./frontend/
    volumes:
      - ./frontend/app:/front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true